### ISSUE TITLE
Wrong permissions on objects.inv?

### ISSUE THREAD

**Issue by msabramo** [zopefoundation/zope.structuredtext#1]
This causes the zope.toolkit Travis CI jobs to fail:

```
WARNING: intersphinx inventory 'http://docs.zope.org/zope.structuredtext/objects.inv' not fetchable due to <class 'urllib2.HTTPError'>: HTTP Error 403: Forbidden
While:
  Installing ztk-docs.
```

**Comment by mgedmin** [comment]
Related: https://github.com/zopefoundation/zopetoolkit/issues/1 (bug about the Travis failure)

Probably related: https://github.com/zopefoundation/zopetoolkit/commit/ce4447e6e0295c3296918948fdc568c1f214201e (commit that made zopetoolkit's docs refer to http://docs.zope.org/)

Incidentally, isn't the plan to drop http://docs.zope.org and start relying on https://readthedocs.org instead?

/cc: @tseaver

**Comment by tseaver** [comment]
This is not-a-bug for zope.structuredtext:  http://docs.zope.org/ is woefully out-of-date (content was generated with a really old version of Sphinx).
