### ISSUE TITLE
Get unit test coverage to 100%

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.structuredtext#3]
And pin it there via `setup.cfg`.

**Comment by jamadden** [comment]
I'm working on this as part of the Python 3.6 support. I have a question:

There are large chunks of stdom.py (a generic DOM-like implementation used by this module; it gets extended it stng.py, e.g., `StructuredTextParagraph(stdom.Element)`) that aren't used at all here. Are those actually necessary, or can they just be deleted? Theoretically they are "public" in that they don't have `_` prefixes and some even have docstrings, but creating a DOM-ish implementation really isn't the point of this package.

I also wonder to a lesser extent about some of the unused public functions found in stng.py. For example, StructuredTextParagraph as mentioned above extends Element. It thus provides an implementation of `getAttribute` which is never called.

**Comment by icemac** [comment]
As this package seems to be one of the lesser used of the ZTK I'd vote for removing the unused code. If there is code in the wild which actually depends on it, we can add it again with proper tests.

**Comment by jamadden** [comment]
OK, I think I will go ahead and merge #6, which still includes all those methods but hits 100% coverage by marking them `#pragma: no cover` so we have a starting point if we need to bring them back. Then I'll open a PR that removes them all (replaces them with `raise NotImplementedError`).
