### ISSUE TITLE
RTD builds broken

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.structuredtext#8]
See http://readthedocs.org/projects/zopestructuredtext/builds/5931436/

It looks like the "install this project" box needs to be checked. I think @tseaver is the RTD owner.

**Comment by tseaver** [comment]
I've updated the project config on RTD to build via a virtualenv, and the [latest branch build passed](https://readthedocs.org/projects/zopestructuredtext/builds/5932657/).

I just restarted the [stable branch build](https://readthedocs.org/projects/zopestructuredtext/builds/5932698/), which should pass as well (AFAIK).

**Comment by jamadden** [comment]
Thank you.
